# -*- coding: utf-8 -*-
"""YuNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OmdX29D_LDziboJ2VSmP0padwYsjbL-d
"""

!pip install --upgrade opencv-python opencv-contrib-python

!wget -O face_detection_yunet_2023mar.onnx https://huggingface.co/opencv/face_detection_yunet/resolve/main/face_detection_yunet_2023mar.onnx

import cv2
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()
img_path = list(uploaded.keys())[0]
print("Uploaded:", img_path)

img = cv2.imread(img_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

model = cv2.FaceDetectorYN_create(
    "face_detection_yunet_2023mar.onnx",
    "",
    (320, 320)
)

h, w = img.shape[:2]
model.setInputSize((w, h))

_, faces = model.detect(img_rgb)

if faces is not None:
    for f in faces:
        x, y, w_box, h_box = f[:4].astype(int)
        cv2.rectangle(img_rgb, (x, y), (x + w_box, y + h_box), (0, 255, 0), 2)

plt.figure(figsize=(8, 6))
plt.imshow(img_rgb)
plt.axis('off')
plt.show()