# -*- coding: utf-8 -*-
"""mtcnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pPBBAHFszyQ5dyPXlsPPjspmI3jeXno
"""

!pip install facenet-pytorch matplotlib opencv-python

from facenet_pytorch import MTCNN
from PIL import Image
import matplotlib.pyplot as plt
import cv2
from google.colab import files

from google.colab import files

uploaded = files.upload()
image_path = list(uploaded.keys())[0]

from PIL import Image
import cv2

img = Image.open(image_path)
img_cv = cv2.cvtColor(cv2.imread(image_path), cv2.COLOR_BGR2RGB)

mtcnn = MTCNN(keep_all=True)

boxes, _ = mtcnn.detect(img)

if boxes is not None:
    for box in boxes:
        x1, y1, x2, y2 = [int(b) for b in box]
        cv2.rectangle(img_cv, (x1, y1), (x2, y2), (0, 255, 0), 2)

plt.figure(figsize=(10,10))
plt.imshow(img_cv)
plt.axis('off')
plt.show()