# -*- coding: utf-8 -*-
"""YOLOv11-face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phNysjhHf_fO7QECbwhRgiJQ1T8CI934
"""

!pip install ultralytics opencv-python-headless --quiet

from huggingface_hub import hf_hub_download

model_path = hf_hub_download(
    repo_id="AlekseyKorshuk/yolov11-face",
    filename="yolov11n-face.pt"
)

from ultralytics import YOLO
from google.colab import files
import cv2
from google.colab.patches import cv2_imshow

model = YOLO(model_path)

uploaded = files.upload()
for fn in uploaded.keys():
    img_path = fn

results = model(img_path)

img = results[0].orig_img.copy()


for box in results[0].boxes.xyxy:
    x1, y1, x2, y2 = map(int, box)
    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)


cv2_imshow(img)