# -*- coding: utf-8 -*-
"""retinaface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GBwzT23vrAbwxpB6PgXjIe00xSA-PZM
"""

!pip install retina-face
!pip install matplotlib opencv-python

from retinaface import RetinaFace
import matplotlib.pyplot as plt
import cv2
from google.colab import files
from PIL import Image

uploaded = files.upload()
image_path = list(uploaded.keys())[0]


img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)


faces = RetinaFace.detect_faces(image_path)


for key in faces:
    face = faces[key]
    x1, y1, x2, y2 = face['facial_area']
    cv2.rectangle(img_rgb, (x1, y1), (x2, y2), (0, 255, 0), 2)


plt.figure(figsize=(10,10))
plt.imshow(img_rgb)
plt.axis('off')
plt.show()